2021-02-19T11:30:11.590+0100	INFO	instance/beat.go:645	Home path: [C:\elasticstack\filebeat-7.10.2-windows-x86_64\filebeat-7.10.2-windows-x86_64] Config path: [C:\elasticstack\filebeat-7.10.2-windows-x86_64\filebeat-7.10.2-windows-x86_64] Data path: [C:\elasticstack\filebeat-7.10.2-windows-x86_64\filebeat-7.10.2-windows-x86_64\data] Logs path: [C:\elasticstack\filebeat-7.10.2-windows-x86_64\filebeat-7.10.2-windows-x86_64\logs]
2021-02-19T11:30:11.637+0100	INFO	instance/beat.go:653	Beat ID: 64b03fb0-5272-4d8f-9002-d370a97446de
2021-02-19T11:30:11.662+0100	INFO	[add_cloud_metadata]	add_cloud_metadata/add_cloud_metadata.go:89	add_cloud_metadata: hosting provider type not detected.
2021-02-19T11:30:11.663+0100	INFO	[beat]	instance/beat.go:981	Beat info	{"system_info": {"beat": {"path": {"config": "C:\\elasticstack\\filebeat-7.10.2-windows-x86_64\\filebeat-7.10.2-windows-x86_64", "data": "C:\\elasticstack\\filebeat-7.10.2-windows-x86_64\\filebeat-7.10.2-windows-x86_64\\data", "home": "C:\\elasticstack\\filebeat-7.10.2-windows-x86_64\\filebeat-7.10.2-windows-x86_64", "logs": "C:\\elasticstack\\filebeat-7.10.2-windows-x86_64\\filebeat-7.10.2-windows-x86_64\\logs"}, "type": "filebeat", "uuid": "64b03fb0-5272-4d8f-9002-d370a97446de"}}}
2021-02-19T11:30:11.664+0100	INFO	[beat]	instance/beat.go:990	Build info	{"system_info": {"build": {"commit": "aacf9ecd9c494aa0908f61fbca82c906b16562a8", "libbeat": "7.10.2", "time": "2021-01-12T23:11:24.000Z", "version": "7.10.2"}}}
2021-02-19T11:30:11.664+0100	INFO	[beat]	instance/beat.go:993	Go runtime info	{"system_info": {"go": {"os":"windows","arch":"amd64","max_procs":2,"version":"go1.14.12"}}}
2021-02-19T11:30:11.673+0100	INFO	[beat]	instance/beat.go:997	Host info	{"system_info": {"host": {"architecture":"x86_64","boot_time":"2021-02-17T10:51:45.88+01:00","name":"AN1CHOVM28","ip":["10.246.9.48/22","172.30.32.1/20","172.17.208.1/20","::1/128","127.0.0.1/8"],"kernel_version":"10.0.14393.4225 (rs1_release.210127-1811)","mac":["00:50:56:85:08:09","00:15:5d:79:11:fa","00:15:5d:3f:3e:8d"],"os":{"family":"windows","platform":"windows","name":"Windows Server 2016 Standard","version":"10.0","major":10,"minor":0,"patch":0,"build":"14393.4225"},"timezone":"CET","timezone_offset_sec":3600,"id":"c25e2fd4-cb5e-4217-81fa-f55b5932fadb"}}}
2021-02-19T11:30:11.673+0100	INFO	[beat]	instance/beat.go:1026	Process info	{"system_info": {"process": {"cwd": "C:\\elasticstack\\filebeat-7.10.2-windows-x86_64\\filebeat-7.10.2-windows-x86_64", "exe": "C:\\elasticstack\\filebeat-7.10.2-windows-x86_64\\filebeat-7.10.2-windows-x86_64\\filebeat.exe", "name": "filebeat.exe", "pid": 14036, "ppid": 6960, "start_time": "2021-02-19T11:30:07.269+0100"}}}
2021-02-19T11:30:11.673+0100	INFO	instance/beat.go:299	Setup Beat: filebeat; Version: 7.10.2
2021-02-19T11:30:11.675+0100	INFO	[publisher]	pipeline/module.go:113	Beat name: AN1CHOVM28
2021-02-19T11:30:11.680+0100	WARN	beater/filebeat.go:178	Filebeat is unable to load the Ingest Node pipelines for the configured modules because the Elasticsearch output is not configured/enabled. If you have already loaded the Ingest Node pipelines or are using Logstash pipelines, you can ignore this warning.
2021-02-19T11:30:11.680+0100	INFO	instance/beat.go:455	filebeat start running.
2021-02-19T11:30:11.680+0100	INFO	[monitoring]	log/log.go:118	Starting metrics logging every 30s
2021-02-19T11:30:11.691+0100	INFO	memlog/store.go:119	Loading data file of 'C:\elasticstack\filebeat-7.10.2-windows-x86_64\filebeat-7.10.2-windows-x86_64\data\registry\filebeat' succeeded. Active transaction id=0
2021-02-19T11:30:11.691+0100	INFO	memlog/store.go:124	Finished loading transaction log file for 'C:\elasticstack\filebeat-7.10.2-windows-x86_64\filebeat-7.10.2-windows-x86_64\data\registry\filebeat'. Active transaction id=0
2021-02-19T11:30:11.692+0100	WARN	beater/filebeat.go:381	Filebeat is unable to load the Ingest Node pipelines for the configured modules because the Elasticsearch output is not configured/enabled. If you have already loaded the Ingest Node pipelines or are using Logstash pipelines, you can ignore this warning.
2021-02-19T11:30:11.692+0100	INFO	[registrar]	registrar/registrar.go:109	States Loaded from registrar: 0
2021-02-19T11:30:11.692+0100	INFO	[crawler]	beater/crawler.go:71	Loading Inputs: 1
2021-02-19T11:30:11.693+0100	INFO	log/input.go:157	Configured paths: [C:\elasticstack\filebeat-7.10.2-windows-x86_64\filebeat-7.10.2-windows-x86_64\logs\test.log]
2021-02-19T11:30:11.693+0100	INFO	[crawler]	beater/crawler.go:141	Starting input (ID: 1455777890333506434)
2021-02-19T11:30:11.694+0100	INFO	[crawler]	beater/crawler.go:108	Loading and starting Inputs completed. Enabled inputs: 1
2021-02-19T11:30:11.694+0100	INFO	cfgfile/reload.go:164	Config reloader started
2021-02-19T11:30:11.694+0100	INFO	cfgfile/reload.go:224	Loading of config files completed.
2021-02-19T11:30:11.694+0100	INFO	log/harvester.go:302	Harvester started for file: C:\elasticstack\filebeat-7.10.2-windows-x86_64\filebeat-7.10.2-windows-x86_64\logs\test.log
2021-02-19T11:30:12.697+0100	INFO	[publisher_pipeline_output]	pipeline/output.go:143	Connecting to backoff(async(tcp://localhost:5044))
2021-02-19T11:30:12.699+0100	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2021-02-19T11:30:12.699+0100	INFO	[publisher]	pipeline/retry.go:223	  done
2021-02-19T11:30:16.572+0100	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2021-02-19T11:30:16.572+0100	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 1 reconnect attempt(s)
2021-02-19T11:30:16.573+0100	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2021-02-19T11:30:16.573+0100	INFO	[publisher]	pipeline/retry.go:223	  done
2021-02-19T11:30:21.425+0100	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2021-02-19T11:30:21.426+0100	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 2 reconnect attempt(s)
2021-02-19T11:30:21.479+0100	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2021-02-19T11:30:21.479+0100	INFO	[publisher]	pipeline/retry.go:223	  done
2021-02-19T11:30:29.115+0100	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2021-02-19T11:30:29.115+0100	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 3 reconnect attempt(s)
2021-02-19T11:30:29.116+0100	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2021-02-19T11:30:29.116+0100	INFO	[publisher]	pipeline/retry.go:223	  done
2021-02-19T11:30:41.799+0100	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":93,"time":{"ms":93}},"total":{"ticks":311,"time":{"ms":311},"value":311},"user":{"ticks":218,"time":{"ms":218}}},"handles":{"open":197},"info":{"ephemeral_id":"ab805eb1-c211-4d64-b0f3-b243dcfaa781","uptime":{"ms":30470}},"memstats":{"gc_next":20116112,"memory_alloc":15447224,"memory_total":48216608,"rss":58171392},"runtime":{"goroutines":31}},"filebeat":{"events":{"active":561,"added":562,"done":1},"harvester":{"open_files":1,"running":1,"started":1}},"libbeat":{"config":{"module":{"running":0},"reloads":1,"scans":1},"output":{"type":"logstash"},"pipeline":{"clients":1,"events":{"active":505,"filtered":57,"published":505,"retry":1515,"total":562}}},"registrar":{"states":{"current":1,"update":1},"writes":{"success":1,"total":1}},"system":{"cpu":{"cores":2}}}}}
2021-02-19T11:30:44.603+0100	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2021-02-19T11:30:44.603+0100	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 4 reconnect attempt(s)
2021-02-19T11:30:44.604+0100	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2021-02-19T11:30:44.604+0100	INFO	[publisher]	pipeline/retry.go:223	  done
2021-02-19T11:31:11.711+0100	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":93},"total":{"ticks":311,"value":311},"user":{"ticks":218}},"handles":{"open":197},"info":{"ephemeral_id":"ab805eb1-c211-4d64-b0f3-b243dcfaa781","uptime":{"ms":60364}},"memstats":{"gc_next":20116112,"memory_alloc":15527272,"memory_total":48296656,"rss":16384},"runtime":{"goroutines":31}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":505,"retry":505}}},"registrar":{"states":{"current":1}}}}}
2021-02-19T11:31:15.302+0100	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2021-02-19T11:31:15.303+0100	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 5 reconnect attempt(s)
2021-02-19T11:31:15.308+0100	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2021-02-19T11:31:15.308+0100	INFO	[publisher]	pipeline/retry.go:223	  done
2021-02-19T11:31:41.685+0100	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":93},"total":{"ticks":311,"value":311},"user":{"ticks":218}},"handles":{"open":193},"info":{"ephemeral_id":"ab805eb1-c211-4d64-b0f3-b243dcfaa781","uptime":{"ms":90357}},"memstats":{"gc_next":20116112,"memory_alloc":15602360,"memory_total":48371744,"rss":61440},"runtime":{"goroutines":31}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":505,"retry":505}}},"registrar":{"states":{"current":1}}}}}
2021-02-19T11:31:50.061+0100	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2021-02-19T11:31:50.061+0100	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 6 reconnect attempt(s)
2021-02-19T11:31:50.062+0100	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2021-02-19T11:31:50.062+0100	INFO	[publisher]	pipeline/retry.go:223	  done
2021-02-19T11:31:50.069+0100	INFO	[publisher_pipeline_output]	pipeline/output.go:151	Connection to backoff(async(tcp://localhost:5044)) established
2021-02-19T11:31:56.914+0100	ERROR	[logstash]	logstash/async.go:280	Failed to publish events caused by: read tcp 127.0.0.1:55162->127.0.0.1:5044: wsarecv: An existing connection was forcibly closed by the remote host.
2021-02-19T11:31:56.915+0100	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2021-02-19T11:31:56.915+0100	INFO	[publisher]	pipeline/retry.go:223	  done
2021-02-19T11:31:56.946+0100	ERROR	[logstash]	logstash/async.go:280	Failed to publish events caused by: client is not connected
2021-02-19T11:31:56.946+0100	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2021-02-19T11:31:56.946+0100	INFO	[publisher]	pipeline/retry.go:223	  done
2021-02-19T11:31:58.638+0100	ERROR	[publisher_pipeline_output]	pipeline/output.go:180	failed to publish events: client is not connected
2021-02-19T11:31:58.638+0100	INFO	[publisher_pipeline_output]	pipeline/output.go:143	Connecting to backoff(async(tcp://localhost:5044))
2021-02-19T11:31:58.639+0100	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2021-02-19T11:31:58.639+0100	INFO	[publisher]	pipeline/retry.go:223	  done
2021-02-19T11:32:03.208+0100	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2021-02-19T11:32:03.208+0100	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 1 reconnect attempt(s)
2021-02-19T11:32:03.208+0100	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2021-02-19T11:32:03.208+0100	INFO	[publisher]	pipeline/retry.go:223	  done
2021-02-19T11:32:11.686+0100	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":109,"time":{"ms":16}},"total":{"ticks":374,"time":{"ms":63},"value":374},"user":{"ticks":265,"time":{"ms":47}}},"handles":{"open":197},"info":{"ephemeral_id":"ab805eb1-c211-4d64-b0f3-b243dcfaa781","uptime":{"ms":120357}},"memstats":{"gc_next":25124352,"memory_alloc":14385264,"memory_total":52127704,"rss":372736},"runtime":{"goroutines":31}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"output":{"events":{"batches":2,"failed":1010,"total":1010},"read":{"bytes":6,"errors":1},"write":{"bytes":24344}},"pipeline":{"clients":1,"events":{"active":505,"retry":2525}}},"registrar":{"states":{"current":1}}}}}
